# Generated by Django 4.2.2 on 2023-06-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laminas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lamina', models.CharField(max_length=255)),
                ('corte', models.CharField(max_length=255)),
                ('montagem', models.CharField(max_length=255)),
                ('aumento', models.CharField(max_length=255)),
                ('coloracao', models.CharField(max_length=255)),
            ],
        ),
    ]
