# Generated by Django 4.2.2 on 2023-06-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laminas',
            name='corte',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
