# Generated by Django 4.2.2 on 2023-06-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laminas', '0002_alter_laminas_corte'),
    ]

    operations = [
        migrations.CreateModel(
            name='estruturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estrutura', models.CharField(max_length=255)),
                ('lamina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laminas.laminas')),
            ],
            options={
                'ordering': ['nome_estrutura'],
            },
        ),
    ]
