# Generated by Django 4.2.2 on 2023-06-07 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laminas', '0003_estruturas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estruturas',
            options={},
        ),
    ]
