# Generated by Django 3.2.12 on 2023-06-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminas', '0005_estruturas_link_estruturas_source_mask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laminas',
            name='imagem_completa',
            field=models.ImageField(null=True, upload_to='scoope/laminas/static/imagens_laminas'),
        ),
    ]
