# Generated by Django 3.2.12 on 2023-06-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminas', '0009_alter_laminas_imagem_completa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estruturas',
            name='mascara',
            field=models.ImageField(null=True, upload_to='imagens_laminas'),
        ),
    ]
