# Generated by Django 3.2.12 on 2023-06-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laminas', '0011_remove_laminas_fullimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estruturas',
            name='source_mask',
        ),
    ]
